### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by XZhang00** [RUCAIBox/Language-Specific-Neurons#1]
Hello! Thanks for your attractive and solid work!

Can you share the link to download the data?

Looking forward to your reply!

**Comment by StevenTang1998** [comment]
Hi, we just download the dataset from https://huggingface.co/datasets/wikipedia.
Then we randomly sample documents to compose 100M tokens for each language.
The dataset file is too large for sharing. You can follow the above instruction to reproduce our results.
If you meet any confusion, feel free to comment here.
