### ISSUE TITLE
About obtaining activations ​​and the linear layer you want to explain

### ISSUE THREAD

**Issue by msra-jqxu** [RUCAIBox/Language-Specific-Neurons#10]
Hi @StevenTang1998 , this is really a very interesting job! 

I have a question that Formula 4 in the paper shows that the gate score is used as the activation value. So is Wdown the linear layer you want to explain? If so, why not use the output features after Wdown? Because using the input features (gate score) of Wdown does not seem to reflect the contribution of its neuron weights. 

Thanks!

![0bd7916887f1369d0ab7fb4b5055dda](https://github.com/user-attachments/assets/ac4c9f2a-44b7-4be5-8f8f-7945abfb4300)

**Comment by StevenTang1998** [comment]
Hi @msra-jqxu,

Thank you for your suggestion! We based our approach primarily on the methodology outlined in [this previous work](https://arxiv.org/pdf/2104.08696), which leverages gate values. The non-linear functions (like ReLU and its variants) lend significance to whether a value is positive or negative in this context. That said, I agree that examining the output features could provide valuable insights, but it would be crucial to ensure that doing so adds to the explainability and robustness of the model. 

Best

**Comment by msra-jqxu** [comment]
Hi @StevenTang1998 ,

Thanks for your reply! By the way, I wonder that when getting the activation value, is the training code or the inference code used? The difference between them is that when predicting the next token, the training code uses the groundtruth text as the context, while the inference code uses the tokens previously predicted by the model as the context. 

Thanks again!

**Comment by StevenTang1998** [comment]
Hi @msra-jqxu ,

It is the same since we obtain the activation value from the FFN regardless of the golden token or the predicted token.
