### ISSUE TITLE
How can I compute LLaMA-2-13B.neuron.pth file on my own machine?

### ISSUE THREAD

**Issue by RadiantCrystal** [RUCAIBox/Language-Specific-Neurons#13]
Hello Authors,

Nice work! Could you please tell me how can I create [LLaMA-2-13B.neuron.pth](https://github.com/RUCAIBox/Language-Specific-Neurons/blob/main/LLaMA-2-13B.neuron.pth) this file for other models? Can you please share the code for that?

**Comment by StevenTang1998** [comment]
You should first download the wiki texts, tokenize them, and run the `activation.py` for each langauge. Then run the `identify.py` to get the `neuron.pth`.

**Comment by RadiantCrystal** [comment]
Hi Steven,

Thanks for your quick response.

Wikitext dataset has multiple rows and column 'texts'. After tokenizing them, for each row I will get input ids. So, if there are K number of rows and P number of tokens in each row, then the input matrix would be P X K. Right? Or how you are expecting to save the input ids?

**Comment by StevenTang1998** [comment]
You concateneate them into a long list just as the packing in pre-training. Then, you can convert them to tensor and save them as `data/id.{lang}.train.llama`.

**Comment by RadiantCrystal** [comment]
So, you mean if I have text like ["I love python", "I learn data science", ..] then it should be converted to input ids like [tensor([0,1,34,3]), tensor([23, 2, 45, 56..])] such numbers right? @StevenTang1998 

Then i convert this list into a tensor (2D --> number of instances X number of token ids) and save it?

**Comment by StevenTang1998** [comment]
> So, you mean if I have text like ["I love python", "I learn data science", ..] then it should be converted to input ids like [tensor([0,1,34,3]), tensor([23, 2, 45, 56..])] such numbers right? @StevenTang1998
> 
> Then i convert this list into a tensor (2D --> number of instances X number of token ids) and save it?

No, you should concateneate the ids in to a 1D long list, like [0,1,34,3, 23, 2, 45, 56..].

**Comment by RadiantCrystal** [comment]
Okay thanks. I did. @StevenTang1998 
Now, I am getting this issue `  File "/home/Avik/Language-Specific-Neurons/activation.py", line 32, in llama_forward
    sum1[idx, :] += activation.sum(dim=(0,1))
RuntimeError: The size of tensor a (11008) must match the size of tensor b (1376) at non-singleton dimension 0`

I was using 8, 24 GB gpus and llama2-7b-chat-hf model. Can you please tell me how to fix this issue?

**Comment by StevenTang1998** [comment]
I responded to it in another issue. It is better to use just one GPU, or you should to conduct a complex modification of the code.

**Comment by RadiantCrystal** [comment]
@StevenTang1998 , how much gpu I need to run this experiment on 7b models?

**Comment by StevenTang1998** [comment]
One 24GB GPU is enough to run 7B models.

**Comment by RadiantCrystal** [comment]
The activation.py part is done. Thank you.

**Comment by RadiantCrystal** [comment]
Hi @StevenTang1998 , I am seeing the following loop in identify.py file. Can I do it for single language as well?

`
n, over_zero = [], [] 
for lang in ['en', 'zh', 'fr', 'es', 'vi', 'id', 'ja']:

    data = torch.load(f'data/activation.{lang}.train.llama-70b')

    n.append(data['n'])

    over_zero.append(data['over_zero'])`

**Comment by StevenTang1998** [comment]
No, the proposed method should be used in several languages since it needs the different activation behaviour in different languages.
