### ISSUE TITLE
Difficulty in understanding the implementation of activation.py

### ISSUE THREAD

**Issue by RadiantCrystal** [RUCAIBox/Language-Specific-Neurons#14]
Hi, I have quite a few doubts about the activation.py code. I have gone through your paper but I would like to understand the code more. It would be great if you could help me in understanding it. @StevenTang1998 

1. Why the sum1, sum2, sum3 and sum4 are defined? Why _power of_ used? Could you please help me to reason better? (Line numbers 20-24 in activation.py)
<pre><code>
sum1 = torch.zeros(num_layers, intermediate_size).to('cuda:0')
sum2 = torch.zeros(num_layers, intermediate_size).to('cuda:0')
sum3 = torch.zeros(num_layers, intermediate_size).to('cuda:0')
sum4 = torch.zeros(num_layers, intermediate_size).to('cuda:0')
over_zero = torch.zeros(num_layers, intermediate_size, dtype=torch.int32).to('cuda:0')
</code></pre>

2. Also I saw some generation is being done in the code but the output never used? Can you please clarify it? Is it for tracing the activations only? (see line number 74 in activation.py)
<pre><code>
output = model.generate(prompt_token_ids=input_ids.tolist(), sampling_params=SamplingParams(max_tokens=1))
</code></pre>

It would be really helpful if you could give some comments around your code or give me a brief about the process followed the the code (from the perspective of implementation)

**Comment by StevenTang1998** [comment]
1. You can ignore the code, since I want to calculate the distribution of activation value, which is irrelevant with my method.
2. My method is irrelevant with generation, and it only needs to record the activation value.
