### ISSUE TITLE
RuntimeError: The size of tensor a (14336) must match the size of tensor b (3584) at non-singleton dimension 0

### ISSUE THREAD

**Issue by RadiantCrystal** [RUCAIBox/Language-Specific-Neurons#15]
Hi @StevenTang1998 , I am getting this issue in activation.py file while running with different data apart from wiki data. Could you please help me to resolve this?

**Comment by StevenTang1998** [comment]
I think it may not be due to the different data. It seems that your should run the code in only one GPU with `CUDA_VISIBLE_DEVICES=0`.
