### ISSUE TITLE
Why I can't find your paper named "Exploring Language-Specific Regions in Large Language Models"? 

### ISSUE THREAD

**Issue by Descartes-Stan** [RUCAIBox/Language-Specific-Neurons#16]
Why I can't find your paper named "Exploring Language-Specific Regions in Large Language Models"? Can I get a private link to your paper?

**Comment by StevenTang1998** [comment]
I have changed the title of the paper, Language-Specific Neurons: [The Key to Multilingual Capabilities in Large Language Models](https://arxiv.org/abs/2402.16438). Thank you for your remind.
