### ISSUE TITLE
max_tokens对于结果的影响，以及gate_up的数据结构问题

### ISSUE THREAD

**Issue by slg6** [RUCAIBox/Language-Specific-Neurons#17]
您好，您的代码让我受益良多，我有一些疑问想请教您一下。

max_tokens的设置对结果有影响吗？我们在实验中设置成1和设置成1024得到的over_zero结果是不一样的。

还有就是我们在实验中，使用llama模型时，在重写forword函数那块，您的源码中读取gate_up[:, :, : i // 2]的方式是三维的，但是我们得到的gate_up这个中间结果是二维，这是和我们的 id.zh.train.llama 文件组织结构相关吗？

实验过程中，我们发现直接使用promts的计算速度要比转为token id更快，但是得到的结果大不一样，直接使用prompts和使用填充的token id进行实验有什么区别吗？

我们使用的vllm版本是0.6.4  这和我们所使用的版本相关吗

**Comment by StevenTang1998** [comment]
1. max_tokens就是context length，这会对结果造成影响；
2. 应该是vllm版本问题，请使用vllm==0.2.7；
3. 这个没有进行过实验，不过我觉得这两个速度在一般情况下应该是一致的，否则很有可能出现问题。
