### ISSUE TITLE
Issue with activation.py - AttributeError in LLMEngine Initialization

### ISSUE THREAD

**Issue by yileitu** [RUCAIBox/Language-Specific-Neurons#3]
Hello Team,

First off, I want to extend my appreciation for your amazing work on this project. I am currently in the process of trying to replicate your results and have encountered an issue that I hope to get some guidance on.

While executing the script `activation.py`, specifically at line 60, I encountered the following error:

```python
obj = model.llm_engine.driver_worker.model_runner.model.model.layers[i].mlp
AttributeError: 'LLMEngine' object has no attribute 'driver_worker'
```
This error was preceded by an INFO log indicating the initialization of an LLM engine:

```arduino
INFO 04-03 16:53:31 llm_engine.py:75] Initializing an LLM engine (v0.4.0) with config ...
```
I suspect this issue might be related to the compatibility of package versions. Could you kindly share the environment requirements that have been proven to successfully run the program? I am particularly interested in the versions of critical packages such as vllm, transformers, torch, and cuda, as well as the version of the LLM engine being used.

If you believe the problem is not related to version compatibility, could you please advise on what else might be causing this issue?

Thank you very much for your support.

**Comment by StevenTang1998** [comment]
We use `vllm==0.2.7`. Thanks for your report!

**Comment by yileitu** [comment]
> We use `vllm==0.2.7`. Thanks for your report!

Problem solved. Thx

**Comment by kkkk-cyber** [comment]
> > 我们使用`vllm==0.2.7`。感谢您的报告！
> 
> 问题解决了。谢谢

Hello, I have a similar problem, my vllm==0.2.7. What are your transformers, torch and cuda versions?

**Comment by StevenTang1998** [comment]
Maybe you can refer to the `requirements` of vllm.

https://github.com/vllm-project/vllm/blob/v0.2.7/requirements.txt
