### ISSUE TITLE
Clarification on Duplicate Thresholds and Redundant Filtering in `identify.py`

### ISSUE THREAD

**Issue by yileitu** [RUCAIBox/Language-Specific-Neurons#4]
Hello,

I've been exploring your implementation of the LAPE method as described in your paper, specifically within the identify.py script. I noticed something that might warrant clarification

In lines 31 and 48 of `identify.py`, there seems to be a repetition in the filtering process using two threshold variables, `filter_rate` and `activation_bar_ratio`, both set at 95%. 
```python
# Line31
top_prob_value = flattened_probs.kthvalue(round(len(flattened_probs) * filter_rate)).values.item()
# Line48
activation_bar = flattened_probs.kthvalue(round(len(flattened_probs) * activation_bar_ratio)).values.item()
```
The paper mentions only one threshold value when introducing the LAPE method, specifically referring to the 95th percentile for filtering. Could you please clarify the reason for the presence of two seemingly identical thresholds in the code? Is there a conceptual difference between these thresholds that necessitates separate applications?

Furthermore, after the initial filtering process where `selected_probs` is derived, there's another filtering step (lines 47-50) to check if `selected_probs` exceed the `activation_bar`.
```python
selected_probs = selected_probs.transpose(0, 1)
activation_bar = flattened_probs.kthvalue(round(len(flattened_probs) * activation_bar_ratio)).values.item()
print((selected_probs > activation_bar).sum(dim=1).tolist())
lang, indice = torch.where(selected_probs > activation_bar)
```

Given that `selected_probs` has already been filtered by the `top_prob_value`, could you explain the rationale behind this additional filtering step? Is this meant to refine the selection further, or does it serve a different purpose?

Understanding the reasoning behind these design choices would greatly enhance comprehension of the LAPE method's implementation and ensure alignment with the conceptual framework outlined in the paper.

Thank you for your time and consideration. I look forward to your response.

**Comment by StevenTang1998** [comment]
The paper has outlined the whole framework. I think you have understood our framework and you don't need to overinterpret our code.

The two variables are just for code implementation. After filtering neurons using `filter_rate`, you should know which language the neuron is specific to, i.e., which language is higher than the threshold `top_prob_value`. This is the function of your highlighted code.
