### ISSUE TITLE
Any plan to upload the activation log on these corpus?

### ISSUE THREAD

**Issue by Z1zs** [RUCAIBox/Language-Specific-Neurons#5]
Hi, thanks very much for your amazing work. When I tried to reproduce the work, it seemed that I will get some strange results during identifying language-specific neurons. Honestly, I 'm not sure if this issue has something to do with the statistical results during activation or the identifying algorithm itself.
If possible, will there be any log files(generated after running activation.py) to publish for localizing root of the problem? I can also report the strange results I have obtained through email if you want (I may not be possible to post it on this issue directly).
Thanks again! You can also email me at 2151773@tongji.edu.cn if uploading those log files is impossible.

**Comment by StevenTang1998** [comment]
Thanks for your question. I have uploaded the intermediate activation results in the repository.

**Comment by Z1zs** [comment]
Thank you very much for your work!!! I really appreciate your kind and timely response!
