### ISSUE TITLE
mistral neuron

### ISSUE THREAD

**Issue by Shimao-Zhang** [RUCAIBox/Language-Specific-Neurons#6]
Hello,

Thanks for this outstanding work! And I notice that you have also conducted the experiments on Mistral-7b. Could you please share the neuron.pth of Mistral if possible?
And how long does it take to get the language-specific neurons from scratch for a 7B model (& what GPU used)?
Thank you!

**Comment by StevenTang1998** [comment]
I have uploaded the results of OPT, Mistral, and Phi-2. As for the evaluation time, it took around 7-8 hours for each language using one 3090 GPU.
