### ISSUE TITLE
Parallel operation error

### ISSUE THREAD

**Issue by YukinoshitaKaren** [RUCAIBox/Language-Specific-Neurons#7]
Hi, I encountered a problem when running _activation.py_. I used 4 A100 to load my model. As a result, in 
```
def llama_forward(self, x):
  gate_up, _ = self.gate_up_proj(x) # b, l, 2i
  i = gate_up.size(-1)
```
An error occurred here.
Because of parallel operation, the tensor was evenly divided into 4 cards, and the size was incorrect. How did you solve this problem?

**Comment by StevenTang1998** [comment]
Yes, I have encountered it. However, it requires complex modifications to the code within the vllm library. Unfortunately, I did not save these changes, and the code was overwritten during my vllm upgrade.

**Comment by YukinoshitaKaren** [comment]
Thank you for your reply. Could you give me some tips?In which direction should I modify the code?I am not very proficient in tensor parallelism.

**Comment by StevenTang1998** [comment]
I remembered that it needs to inherit the `Worker` class of vllm (LLMEngine._init_workers) and change the behavior of `load_model`.

**Comment by YukinoshitaKaren** [comment]
Thank you, I will try

**Comment by YukinoshitaKaren** [comment]
I tried to use `tensor_model_parallel_all_gather` to get the complete tensor slice, which seemed to work, but the result was slightly different from the single-card run. In the attention layer, the hidden state of the single-card and multi-card had a difference of **0.001**, and ultimately led to a large difference in the identified neurons? Can this error be avoided?
And when I was running `generation.py`, I found that even if I got the complete tensor slice, I didn't know how to cut the modified (activation value set to 0) tensor into four parts and pass it back. I don't know how to solve this problem

**Comment by StevenTang1998** [comment]
I did not use the `tensor_model_parallel_all_gather` function. However, I may have encountered similar problems before, since tensor parallelism splits the hidden state. You need to pay attention to the different meanings of the first half and the second half of the hidden state on the same GPU, and the neuron indice of different GPUs are different when generating.

**Comment by YukinoshitaKaren** [comment]
I found that `obj.forward = MethodType(factory(layer_mask.to('cuda')), obj)` can only replace the forward of `cuda:0`. On other GPUs, it still runs according to the original forward function. How do you solve this problem?

**Comment by StevenTang1998** [comment]
I remembered that I did not change this function.

**Comment by RadiantCrystal** [comment]
Hey @StevenTang1998 , I have facing the same `    sum1[idx, :] += activation.sum(dim=(0,1))
RuntimeError: The size of tensor a (11008) must match the size of tensor b (1376) at non-singleton dimension 0` issue while running on multiple gpus. Can you pass the updated activation.py code file?

**Comment by RadiantCrystal** [comment]
Hello @YukinoshitaKaren, as you mentioned earlier that you attempted to rectify this issue, if you have the updated code, can you please share it?

**Comment by StevenTang1998** [comment]
> Hey @StevenTang1998 , I have facing the same ` sum1[idx, :] += activation.sum(dim=(0,1)) RuntimeError: The size of tensor a (11008) must match the size of tensor b (1376) at non-singleton dimension 0` issue while running on multiple gpus. Can you pass the updated activation.py code file?

Sorry, I cannot find the code running in multiple GPUs. I just remember you can adjust the vllm code itself or insert the code just as `activation.py` to achieve this. It took me a long time to deal with it. So it is better to use a GPU.

**Comment by YukinoshitaKaren** [comment]
> Hello @YukinoshitaKaren, as you mentioned earlier that you attempted to rectify this issue, if you have the updated code, can you please share it?

```
def llama_forward(self, x):
            gate_up2, gate_up1, _ = self.gate_up_proj(x)  # l, 2i
            # gate_up22 = tensor_model_parallel_gather(gate_up2, dst=0)
            gate_up = gate_up1.clone()
            i = gate_up.size(-1)
            num_chunks = 8
            splits = torch.split(gate_up, gate_up.size(-1) // num_chunks, dim=-1)
            reordered_splits = [splits[i] for i in [0, 2, 4, 6, 1, 3, 5, 7]]
            gate_up = torch.cat(reordered_splits, dim=-1)
            gate_up[:, : i // 2] = torch.nn.SiLU()(gate_up[:, : i // 2])
            activation = gate_up[:, : i // 2].float()  # l, i
            sum1[idx, :] += activation.sum(dim=0)
            sum2[idx, :] += activation.pow(2).sum(dim=0)
            sum3[idx, :] += activation.pow(3).sum(dim=0)
            sum4[idx, :] += activation.pow(4).sum(dim=0)
            over_zero[idx, :] += (activation > 0).sum(dim=0)
            cnt[idx] += 1
            # y = gate_up[:, : i // 2] * gate_up[:, i // 2 :]
            # y, _ = self.down_proj(y)
            i = gate_up2.size(-1)
            gate_up2[:, : i // 2] = torch.nn.SiLU()(gate_up2[:, : i // 2])
            x = gate_up2[:, : i // 2] * gate_up2[:, i // 2 :]
            x, _ = self.down_proj(x)            
            return x
```
And, modify `llama.py` in the VLLM library on line 88: 

```
def forward(self, x):
        gate_up, gate_up2, _ = self.gate_up_proj(x)
        x = self.act_fn(gate_up2)
        x, _ = self.down_proj(x)
        return x
```

And `linear.py `on line 329:

```
def forward(self, input_):
        bias = self.bias if not self.skip_bias_add else None
        # Matrix multiply.
        assert self.quant_method is not None
        output_parallel = self.quant_method.apply(self, input_, bias)
        if self.gather_output:
            # All-gather across the partitions.
            output = output_parallel
            output2 = tensor_model_parallel_all_gather(output_parallel)
            output_bias = self.bias if self.skip_bias_add else None
            return output, output2, output_bias
        else:
            output = output_parallel
        output_bias = self.bias if self.skip_bias_add else None
        return output, output_bias
```
   **The core idea is to return all tensors to the first GPU for operation**

**Comment by RadiantCrystal** [comment]
@YukinoshitaKaren Hey, thank you so much. I will try it out. :)
