### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by clarence-lee-sheng** [RUCAIBox/Language-Specific-Neurons#8]
Hi, I love your work and it is very interesting! Do you happen to have a requirements.txt for your project which we can use? 

Thank you!

**Comment by StevenTang1998** [comment]
Thank you for your suggestions! Unfortunately, I didn't create a requirements file at that time, and my environment has since been updated. From what I recall, my libraries were using the latest versions available around December 2023, for example, vllm==0.2.7.
